language: node_js
node_js:
  - "node"

before_install:
  - make install-test-dependencies

script:
  - make check-syntax
  - make run-tests-with-coverage

after_success:
  - make push-coverage-raport
