name: Build

on: 
  release:
    types: 
    - published

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i
    - name: Checkout to production
      run: git checkout -B production
    - name: Run build
      run: npm run-script build
    - name: Add dist directory
      run: git add -f /dist
    - name: Change tag
      run: git tag -fa "${GITHUB_REF}"
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action" 
        git commit -m "Release: ${GITHUB_REF}" | echo
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      env:
        CI: true
